---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "pvala-cluster"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    name: "pvala-cluster-control-plane"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    name: "pvala-cluster-control-plane"
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
metadata:
  name: "pvala-cluster-control-plane"
spec:
  region: "ap-south-1"
  version: "v1.28"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "pvala-cluster-pool-0"
spec:
  clusterName: "pvala-cluster"
  template:
    spec:
      clusterName: "pvala-cluster"
      bootstrap: 
        dataSecretName: ""
      infrastructureRef:
        name: "pvala-cluster-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: "pvala-cluster-pool-0"
spec:
  instanceType: t3.medium
